### ISSUE TITLE
Safari JS error prevents use

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-studio-classic#102]
Any use on Safari causes a JS error in the console and no tiles show up. 

```
[Error] TypeError: 'undefined' is not an object (evaluating 'map.options.minZoom = this.model.get('minzoom')')
    refresh (style, line 3158)
```

![screen shot 2014-01-15 at 4 40 45 pm](https://f.cloud.github.com/assets/17722/1926611/fe9d55d2-7e46-11e3-80a2-55e935ccbff1.png)

**Comment by springmeyer** [comment]
Somehow the global `map` variable is getting set in Safari to `<div id=​"map" style=​"background-color:​rgba(255,255,255,1.00)​;​">​</div>​` such that the map is never initialized because is not undefined here: https://github.com/mapbox/tm2/blob/527458cb989b652bf2b2a79a3fde889a4309f86f/templates/style._#L433
