### ISSUE TITLE
mapnik-omnivore may return error when detecting extent

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#1156]
https://github.com/mapbox/mapbox-studio/blob/mb-pages/lib/source.js#L306

`results` here can be an error. Handle accordingly. Ran into this working with @andreasviglakis

**Comment by springmeyer** [comment]
See also #1111

**Comment by springmeyer** [comment]
Also just replicated: I think this is happening because the `geometry_table` is not able to be detected. This was failing silently but will start to fail harder (beforehand) after https://github.com/mapnik/mapnik/commit/4a1f4a9b5ea30b79dfd7dfa9f683ef57c52f3278 because `geometry_table_` is unknown/undetected for complex queries. So the solution is to either require `geometry_table` be supplied or require the `srid` is supplied (to allow mapnik to be  able to skip querying the geometry_table), or both.

**Comment by springmeyer** [comment]
Running this patch locally and seems to be working:

``` diff
diff --git a/lib/source.js b/lib/source.js
index bee3028..302f4d2 100644
--- a/lib/source.js
+++ b/lib/source.js
@@ -308,6 +308,7 @@ source.extent = function(data) {
         var ds = new mapnik.Datasource(opts);
         var results = getExtent(ds, l.srs);
         var extent = results.extent;
+        if (!extent) return [-180,-85.0511,180,85.0511];

         // Take the greater coordinate to make sure all layers are included in the final extent
         memo[0] = Math.max(-180, Math.min(extent[0], memo[0]));
```

**Comment by springmeyer** [comment]
Noting that #1199 takes a different approach and starts throwing (https://github.com/mapbox/mapbox-studio/pull/1199/files#diff-ae2e9ce210cf8e5e189658fb547ddc8aR310). So, we'll want to confirm that whatever was originally causing the null extent is fixed. Otherwise we'll just be replacing the current error with a new error.

**Comment by springmeyer** [comment]
This was fixed by https://github.com/mapbox/mapbox-studio/commit/8c07114cbee13043a3071ba08cf11dd16187f060. Obviously returning the default extent will lead to more tiles being rendered, so this solution is not totally ideal. But we can handle that issue separately.
