### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by MarkWS** [mapbox/mapbox-studio-classic#1194]
I know the last issue was closed but we are still unable to start up.
I've removed the `app.db` file in the `.mapbox-studio` user directory and the program will start up. But then only once, so we are having to remove the `app.db` file each time to get the program to load.
Have reverted to v 0.2.2 and it's the same issue there, crash while loading.
Win 7 Pro 64bit

**Comment by springmeyer** [comment]
@MarkWS - Can you also try restarting your machine? See if that helps?

If not then the problem is likely that a project file has become invalid. By default Studio opens to the last project you edited and so if the last project is broken this can prevent Studio from opening. Removing the `app.db` temporarily works around this by stopping Studio from opening the last project immediately. But if you navigate to the broken project you'll likely end up in the same state.

**Comment by MarkWS** [comment]
restart didn't help.
and this doesn't seem related to the projects. once we remove the `app.db` file the program loads. Then we 'connect' to our account, 'allow' in the authorize page and in the new project page we chose 'blank source'
then close MBS and it will not start up. so we have not loaded any projects and only started with a blank source without saving it.

**Comment by samanpwbb** [comment]
@MarkWS are you using [templates and interactivity layers](https://www.mapbox.com/mapbox-studio/style-quickstart/#utfgrid-interactivity) in any of your styles?

**Comment by MarkWS** [comment]
No, we are not.

**Comment by wilhelmberg** [comment]
Can you verify via `Windows Task Manager` that there are no `mapbox-studio.exe` or `node.exe` processes running after the crash?

![image](https://cloud.githubusercontent.com/assets/4549888/6244292/b8f527f4-b751-11e4-830b-a148551695de.png)

If there are any, please kill them, via `Right Click -> End Process Tree` before proceeding.

---

Maybe some kind of permission problem?
Could you try to remove `%USERPROFILE%\.mapbox-studio` completely before starting Studio?

---

If deleting the directory doesn't help, it would be great if you could follow these steps to help find the problem.
- download and extract [ProcDump](https://technet.microsoft.com/en-us/sysinternals/dd996900.aspx) to a directory of your choice.
- `cd` into that directory on a command prompt:
  - press Windows-Key + R
  - type `cmd`, press Enter
  - type `cd <FULL-PATH-TO-EXTRACTED-PROCDUMP>`, press Enter
- start ProcDump:
  - type `procdump -w -ma -e 1 -l -t node.exe`, press Enter
  - you should see

![image](https://cloud.githubusercontent.com/assets/4549888/6244209/5b79033a-b750-11e4-8fe0-28f090f08195.png)
- start Mapbox Studio
  - when Mapbox Studio crashes you should see something like this:
    ![image](https://cloud.githubusercontent.com/assets/4549888/6244151/99054098-b74f-11e4-95b1-f135f45c7641.png)
  - the `DMP` files can be huge, but the compress really well with [7z](http://www.7-zip.org/download.html) and compression set to `Ultra`.
- share the zipped `DMP` files, so that we can take a look

**Comment by wilhelmberg** [comment]
When you are on the command prompt, enter those commands:

```
ECHO %GDAL_DATA%
ECHO %PROJ_LIB%
ECHO %ICU_DATA%
```

Do they output a path, like `C:\some\other\program\GDAL-DATA` or `%GDAL_DATA%`?

**Comment by MarkWS** [comment]
removal of the `.mapbox-studio` folder in the `users` dir worked.
the program did not crash on start-up when using v 0.2.2
upgraded to v 0.2.5 and it seems to be working fine. Will be working in MBS all day so I'll keep you posted.

**Comment by MarkWS** [comment]
more on this issue. I would consider this closed. the removal of the `.mapbox-studio` folder has solved this problem.
