### ISSUE TITLE
Image filter blur: blocky rendering at certain percentages

### ISSUE THREAD

**Issue by tedmcdo** [mapbox/mapbox-studio-classic#1252]
I have been trying to create a smooth gradient like effect with my #landuse.park layer. I am using image-filters:agg-stack-blur(); to create this effect. However, after going above about 30% on the blur, the smooth blur starts to abruptly cut off in some areas (you can see it in the attachment). This happens at all zoom levels.

Am I doing something wrong? 

![screen shot 2015-03-14 at 5 43 30 pm](https://cloud.githubusercontent.com/assets/8085589/6654253/81962138-ca74-11e4-894c-b79ec8a7c51d.png)

**Comment by springmeyer** [comment]
you are not doing anything wrong. for blurring to be seamless - because rendering is per tile - the underlying data in the vector tiles needs to be buffered. for example if the tiles have a buffer of 8 then it is safe to use a radius x and radius y of up to 8. any higher and you will see these kinds of blocky artifacts.

**Comment by tedmcdo** [comment]
Makes sense, thanks.
