### ISSUE TITLE
Middleware silently failing

### ISSUE THREAD

**Issue by camilleanne** [mapbox/mapbox-studio-classic#1262]
In #1250, middleware was silently failing so it took a long time for us to track down a url format bug that is keeping styles from getting loaded.  The middleware can't load the correct style [here](https://github.com/mapbox/mapbox-studio/blob/b064544dbdaf07e367411df343b773723547c1c5/lib/middleware.js#L139), so it fails silently and defaults to the tmp style.

@springmeyer said he'd found other examples of this where `SQLITE_BUSY` errors are getting suppressed when loading sources.

cc @springmeyer @yhahn

**Comment by springmeyer** [comment]
Update here:
- Yes, I've seen (with mapbox-streets locally) that a debugging change like https://github.com/mapbox/mapbox-studio/compare/middleware-conspiracy will reveal `SQLITE_BUSY` errors that otherwise go silent.
- However I've run that same patch a couple times while testing #1267 and found no console logs showing up. So, I think I was on the wrong track to expect they would.
- So, let's keep this ticket open only as a reminder for me to try to track down exactly where the `SQLITE_BUSY` errors were coming from.

**Comment by springmeyer** [comment]
tracked down the line numbers of errors, now tracking at #1284
