### ISSUE TITLE
crashes with exit code 8 on upload/export to MBTiles

### ISSUE THREAD

**Issue by jmcbroom** [mapbox/mapbox-studio-classic#1325]
I'm trying to upload a source with layers from PostGIS -- Mapbox Studio shuts down immediately as soon as I click "upload to Mapbox" or "export to MBTiles". I've tried deleting app.db, ~/.mapbox-studio, and the program itself. any ideas?

**Comment by springmeyer** [comment]
This is a bug in the current release. It is fixed in the development code (https://github.com/mapbox/mapbox-studio/pull/966#issuecomment-85589626). So, possible workarounds for you until we find time for a new release:
- Build from source: https://github.com/mapbox/mapbox-studio#install-from-source
- Very carefully edit your `C:\Program Files\mapbox-studio\resources\app\lib\source.js` file with this patch: https://github.com/mapbox/mapbox-studio/pull/966/files. Then restart and try again.

**Comment by jmcbroom** [comment]
the development version is working - thanks for the quick reply.
