### ISSUE TITLE
maxzoom-slider still has max 16 

### ISSUE THREAD

**Issue by stvno** [mapbox/mapbox-studio-classic#1340]
In mapbox-studio 0.2.7 win64 the maxzoom slider for a new source only goes to 16. The changelog for 0.2.7 states 'Update minzoom / maxzoom maximium slider value to 16 from 22', but if I check the code *) the maximum is still 16, which prevents users from making tilesets beyond zoomlevel 16.

*) https://github.com/mapbox/mapbox-studio/blob/mb-pages/templates/source.html#L94

**Comment by stvno** [comment]
Oh never mind I read it the wrong way around, I assumed the idea was to increase the maxzoom to 22, but instead it was decreased to 16. Any particular reason to disallow the higher zoomlevels?

**Comment by ajashton** [comment]
Most data should not need a maxzoom higher than 16 due to [overzooming](https://www.mapbox.com/guides/source-manual/#overzooming). Even if you want to display the data at higher zoom levels, most street-level map data only needs a maxzoom of 14 or 15.

If you really do need a higher maxzoom you can manually set one in data.yml, but we've updated the limits in the UI to cut down on the number of data uploads that are unintentionally much larger than they need to be (and would take many hours or even days to export).

**Comment by springmeyer** [comment]
> If you really do need a higher maxzoom you can manually set one in data.yml, but we've updated the limits in the UI to cut down on the number of data uploads that are unintentionally much larger than they need to be.

What about adding this to the changelog and docs /cc @amyleew

**Comment by stvno** [comment]
I thought so too, but setting the maxzoom in data.yml or even data.xml is quite tricky because everytime you open the source in mapbox-studio the maxzoom is overwritten by the application. In the end I modified template/source.html with a higher maxzoom to prevent it from overwriting the maxzoom in data.yml

I'm aware that with overzooming zoomlevel 16 is normally fine, it was just a very specific usecase where I needed high res vectortiles

**Comment by amyleew** [comment]
@stvno - Make sure Studio is closed when you update your data.yml. When you restart Studio there should be no overwrite issues.
