### ISSUE TITLE
fail to build from source on gentoo

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapbox/mapbox-studio-classic#1341]
On gentoo I cloned the repository and the launched the command npm install --build-from-source inside the dir, but fails.
Output here
https://gist.github.com/Alessandro-Barbieri/ce9039621a099ce6c666

**Comment by springmeyer** [comment]
Gentoo is not a platform we've packaged binaries for and so you are correct to pass `--build-from-source`. It is failing because you don't have Mapnik installed. I recommend running on Ubuntu Trusty because then you don't need the `--build-from-source` and you don't need Mapnik installed. If you are determined to run on Gentoo, then first start by building Mapnik. Create issues at https://github.com/mapnik/mapnik-support/issues if you have trouble.
