### ISSUE TITLE
Timeout after 5000ms

### ISSUE THREAD

**Issue by gcoop** [mapbox/mapbox-studio-classic#1383]
I keep getting the timeout error when using Mapbox. Often immediately after I open it. I can reproduce on demand by trying to add a custom source or by trying to create a new project with the dark base layer.

If I open the dev tools it looks like many of the requests are returning a 500. Requests like: http://localhost:3000/new/style?id=tmpstyle:///Applications/Mapbox%20Studio.app/Contents/Resources/app/node_modules/mapbox-machine-styles/node_modules/mapbox-studio-dark

**Comment by gcoop** [comment]
I'm not behind a proxy or firewall :)

**Comment by springmeyer** [comment]
Thanks for the report @gcoop. The styles are stored locally but they depend on vector tiles dynamically downloaded from tile.mapbox.com. My hunch is this due to slow network between you and tile.mapbox.com or some unexpected latency on the mapbox end. Can you let us know if it persists tomorrow or next time you try the app? /cc @willwhite

**Comment by gcoop** [comment]
Hmmm no requests to tile.mapbox.com

![screen shot 2015-06-12 at 8 38 17 pm](https://cloud.githubusercontent.com/assets/266345/8142868/fbf197b8-1142-11e5-989a-62b94bf554a6.png)

I ran a speed test on my line and I'm getting 50mbps down and 10 up.

**Comment by gcoop** [comment]
Ok something really odd is happening for me, it must be local. If I connect to a VPN it works fine...
