### ISSUE TITLE
Convert spatialite to mbtiles?

### ISSUE THREAD

**Issue by bmehta** [mapbox/mapbox-studio-classic#1492]
Is there a way to convert spatialite to mbtiles using mapbox studio?

**Comment by springmeyer** [comment]
If https://github.com/mapbox/mapnik-omnivore were to gain knowledge of `sqlite` files then Mapbox Studio Classic could support them directly since Mapnik supports sqlite (with spatialite geometries). But until then you'll need a workaround. I recommend you convert your data to another format that is supported like GeoJSON, or Shapefile. Then load that file in as a new "Source". Then you can create an mbtiles containing vector tiles. Does that help?

/cc @lyzidiamond

**Comment by springmeyer** [comment]
@bmehta - I stand corrected. SQlite files (containing either WKB geometries or spatialite geometries) should be supported: Just click the `SQLite` word on the lower part of the data loading UI rather than clicking "Browse":

![screenshot_from_2015-10-28_18_11_26_360](https://cloud.githubusercontent.com/assets/20300/10804787/971e889a-7d86-11e5-9818-bf47513a299a.png)

And then let us know if you have any trouble. Please create a new issue if you do have trouble.
