### ISSUE TITLE
Zoom level in Settings

### ISSUE THREAD

**Issue by bmehta** [mapbox/mapbox-studio-classic#1505]
I have a spatialite file that I export to mbtiles using mapbox studio classic. In the "Settings" section I see that the max value for Maxzoom that is supported is only 16 (see screenshot). 

![image](https://cloud.githubusercontent.com/assets/1613279/11187580/fd935484-8c54-11e5-98a5-88702ed997fa.png)

I believe that mapbox gl js supports a max zoom of 22. Is there a way for me to export out to that zoom level?

Thanks.

**Comment by wilhelmberg** [comment]
@bmehta `Maxzoom=16` for source projects should be sufficient for maps displayed up to 22.
Because of overzooming.

"_As a general rule, vector tiles are useful for about 4-6 levels of overzooming. For example, the data in a zoom level 14 tile can be stretched out and look great up to zoom level 18 or 20._"

Please see
https://www.mapbox.com/help/getting-started-studio/#minzoom-maxzoom
and
https://www.mapbox.com/help/source-manual/#overzooming
