### ISSUE TITLE
Native file browser

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-studio-classic#230]
Is there a technical reason why we are not using a native file picker/browser for adding sources? It seems a little overkill to reinvent the wheel and create our own.

Plus, there are advantages to using the systems file browser for adding sources:
- Recent places
- Tagged folders
- Familiar
  
  cc @tristen @samanpwbb

**Comment by kkaefer** [comment]
See https://github.com/mapbox/tm2/pull/227#issuecomment-37940499.

We discussed this in chat. The reason is that the native browser does not divulge the absolute file system path, but returns something like `C:\fakepath\file.ext`. However, we need to send the path from the client to the server because it needs to read/write from there.

**Comment by incanus** [comment]
Background as well: https://github.com/mapbox/tilemill/issues/907

We could do this on certain platforms if it's not a lot of code. The TM1 picker always gets me when it comes to not remembering my place, not having access to keyboard shortcuts like `Cmd-D`, not having quick access to the data folder I've bookmarked in the sidebar, etc.

**Comment by zeke** [comment]
> the native browser does not divulge the absolute file system path

What does it divulge? Seems like there's gotta be a way to work around this. In my experience working with TM2, browsing for files is the most frustrating interaction.

**Comment by tristen** [comment]
> What does it divulge? 

It doesn't pass an absolute path which is currently required when accessing tm2 files.

**Comment by zeke** [comment]
Yeah I guess this is an obvious security risk. I wonder if wrapping tm2 in something like webkit.js or node-webkit would help.

**Comment by springmeyer** [comment]
I've been paying some attention to node-webkit - it looks to be extremely sophisticated and I've sought to support it with node-pre-gyp binaries in part to make this possible to experiment with. Though I've always been turned away by the extra size you pay for, at least compared to using system webkit on OS X like we do now.

**Comment by incanus** [comment]
Just because we can't do this universally for _all_ web clients doesn't mean we shouldn't do it for _some_ native clients. Choosing an absolute file path and passing that to the server is clearly a security risk for the web globally, but makes the most sense from a user point of view for an operation that is repeated many times throughout the editing of a project. Yes, it's code branching, but it's a clearly superior user experience. 

Tagging https://github.com/mapbox/tm2/issues/110 here as something to consider in that work. Fallback could remain the current HTML-based picker, but a future possible native app bundle could do a native picker.

**Comment by zeke** [comment]
Hey y'all. I'm sure you heard about the open-sourcing of atom.io, but did you see atom-shell?! This could be a good fit for tm2: https://github.com/atom/atom-shell/blob/master/docs/tutorial/quick-start.md

**Comment by springmeyer** [comment]
Thanks @zeke! Yes, I poured over atom-shell this morning - looks very very interesting as a wrapper. The trick it looks like would be to have it be optional - you should be able to launch tm2 either as an atom shell app or just a server process. The other issue is that native addons would need to be rebuilt against node v0.11.x. So atom-shell is not going to work until I port [node-mapnik to use NAN](https://github.com/mapnik/node-mapnik/issues/252)
