### ISSUE TITLE
Expose zoom level ranges for different classes, types, etc of each data layer in the data sidebar?

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-studio-classic#234]
Some subsets of data layers are available at different zoom levels. Right now we only display a blanket range of available zoom levels for each layer:
![screen shot 2014-03-21 at 7 02 03 pm](https://f.cloud.github.com/assets/5607844/2488855/db389da2-b14c-11e3-93b0-1a10e3105cff.png)

Is there any way to add more specificity here? E.g. what zoom levels are available for the street_limited class of road? Would this add too much info to the interface?

**Comment by ajashton** [comment]
There isn't a good way to automatically determine this, and we wouldn't want to anyway since this is only useful to know for a few specific fields. Adding it manually would be possible, but the UI isn't really conducive to this.

Perhaps a separate place to capture more detailed documentation like this would be useful. Like a readme, but stored in the source so you can access it while styling. (The 'Description' field could be this, but it doesn't actually get displayed anywhere yet? Also no idea how this would be handled when compositing sources.)

Examples of other things that aren't captured anywhere discoverable:
- the difference between 'class' and 'type'
- how our osm_ids are different from actual osm_ids
- what do 'main', 'street_limited', etc actually mean?

**Comment by skorasaurus** [comment]
+1 to that. I was curious, for example, if I could differentiate by type of sport used.

**Comment by yhahn** [comment]
https://www.mapbox.com/developers/vector-tiles/mapbox-streets/ for now.
