### ISSUE TITLE
Closing and deleting

### ISSUE THREAD

**Issue by nilshoerrmann** [mapbox/mapbox-studio-classic#244]
I really like the direction TM2 is heading to but if you are new to the UI, there are a few confusing aspects:

![tm2](https://f.cloud.github.com/assets/25466/2523788/49e8626e-b4d6-11e3-9c2b-b8580145e734.png)
1. What is the `x` button for? Even if you understand that the close button overlays the icon of the current area, you loose context.
2. The style deletion UI makes the action ifself very prominent as if it's something you should do immediately. It's also quite close to the create new button which might lead to false clicks.
3. What's the name/content of the currently selected panel? The corresponding icon is hidden, see 1, so I'm missing the context. It would be neat to have a fixed header with the panel title and a close button (so that the icon could stay visible as well).

By the way, is there a reason behind the different colours of the panels (dark vs. light)?

**Comment by aaronlidman** [comment]
Yeah I agree, all good points.

Saman is working on replacing the `x` here: https://github.com/mapbox/tm2/pull/212 but maybe we should have an `x` for the style tabs instead of the trash can, to look like most web browsers?

**Comment by samanpwbb** [comment]
Thanks for the feedback. All good points. 

Here are my thoughts:

> What is the x button for?

I've been back and forth on `trash` vs `x` icon meanings in TM2. Right now, `x` is _always_ for exiting state, never for manipulating projects or data. On the other hand, trashcans are _always_ for making a change that is saved permanently in the project. Note that under no circumstances does TM2 _actually_ delete files from a user's file system, it only ever removes reference to them.

It's important that symbols continue to have consistent meaning, and I still think `x` for exiting state and 'trash' for permanent change works. Next step will be to do a better job showing active state (for example, rather than representing drawer active state with a `x`, show it with a highlighted icon). This might lead me to free up the `x` symbol so I can use it instead of `trash` on stylesheets and projects.

> The style deletion UI makes the action itself very prominent

Better separation between `trash` icon and rest of the tab will help. I will meditate on this more - but I think this will work well after that adjustment. There's a confirm modal so an accidental click is not the end of the world.

> What's the name/content of the currently selected panel?

Most panels have a heading. Data inspect panel doesn't - I will fix this.

> is there a reason behind the different colours of the panels

Dark -> related to inspecting/editing sources, Blue -> related to managing _external stuff_ and White -> related to style. Open to suggestions for making this clearer.

**Comment by nilshoerrmann** [comment]
A few more thoughts:

#### Regarding trash and delete actions

> I've been back and forth on trash vs x icon meanings in TM2. Right now, x is always for exiting state, never for manipulating projects or data.

I think this concept works just fine and seems to be used consistently across the interface – the user should understand that difference. My point is actually about the positioning and visibility of those actions. Although I understand that `x` closes something, it hides _what_ I'll be closing – that's the issue, not the used metaphors for the actions.

> Note that under no circumstances does TM2 actually delete files from a user's file system, it only ever removes reference to them.

This on the other hand is something I won't have guessed. For me, the trash icon refers to a permanent action (maybe I'd expect an undo option but in general I'd think the file will be gone). So what about these unlinked files? Can I somehow bring them back to the interface?

If yes, why don't you use an unlink icon instead on a trash icon?
If no, why isn't it actually deleted?

#### Regarding colours

> Dark -> related to inspecting/editing sources, Blue -> related to managing external stuff and White -> related to style.

While that is a very logical setup, the interface currently seems to have only three different kind of panels and those panels have a different colour each. As long as there won't be a significant number of additional panels (and related buttons/icons) I'm not sure if the colour distinction is needed at all.

Maybe the colours try to solve another problem that I'm not actually sure they can solve: there are two different kind of actions in the right header: buttons and tabs. Buttons open the panel to the left, tabs open content (= styles) below the header. But visually the header looks like either a list of buttons _or_ a row of tabs. I understand why there is a content area and a side panel, but I think the toolbar is not very clear on what the different items do and where they do it in the interface.

**Comment by samanpwbb** [comment]
> If yes, why don't you use an unlink icon instead on a trash icon?

To user, delete actions delete references to files. That makes them disappear from the UI. Unlink icon is ambiguous.

I am closing now, the original issues brought up here have been addressed. Thanks for the input @nilshoerrmann
