### ISSUE TITLE
codemirror swatch bug

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#274]
![2014-04-02 11_29_53](https://cloud.githubusercontent.com/assets/108094/2593022/ab290042-ba7b-11e3-8a0f-525211b71200.gif)

existed even before #273

**Comment by nilshoerrmann** [comment]
The editor also "forgets" to show colours sometimes, e. g. if you are editing a list of color variables, the new colour will not be shown instantely. 

In this context, I noticed that it's not very easy to scan for colours because they are always at the end of a line and thus their position jumps around depending on the lenght of the different style declarations. It might be helpful to move the colour preview to the beginning of the line, maybe even inside the area where the line numbers are displayed.

**Comment by samanpwbb** [comment]
@nilshoerrmann yeah, the swatches have a lot of issues right now. I'll look into what I can do to remedy the situation.

**Comment by samanpwbb** [comment]
Closing, fixed this and related problems in https://github.com/mapbox/tm2/pull/394
