### ISSUE TITLE
Unable to open project that has an error in it

### ISSUE THREAD

**Issue by skorasaurus** [mapbox/mapbox-studio-classic#286]
so, one of my projects that I opened had an error in it and I managed to save it with the error. 

When I tried to open the project again in tm2 (using the current master), https://github.com/mapbox/tm2/commit/e599c65b2451e0ad634a2fd37403aabfebf8840f
I receive an error message and prompted to hit back. Once I hit back, I am at the default project instead of my project. 

screen shot of this: 

![selection_043](https://cloud.githubusercontent.com/assets/955351/2662789/c52d0dc4-c045-11e3-8ebf-4c32a97e4a82.png)

A fix for this would be to expose the editor so the user can fix their error and continue on their merry way of editing their map.

**Comment by yhahn** [comment]
Going to say no to this for now. The approach we're going to take is to try to make sure invalid projects can't be saved rather than making project loading totally open to any kinds of errors.

The case above was a rare where a major switch was made (mapnik `strict: true`) and it's changes like this that make pre-relase atm.
