### ISSUE TITLE
Ditch dirty?

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#324]
node-dirty in [TileMill 1](https://github.com/mapbox/tilemill/issues/2032) has shown corruption problems.

And node-dirty is not working in TM2 on windows leading to permissions errors trying to open the db (#315).

What about using node-sqlite3?

**Comment by yhahn** [comment]
Hrm, I've implemented boot-time compaction of the node-dirty DB at boot time for this very reason. I'd like to stay away from node-sqlite3 and other DBs as it's much easier to use the synchronous interface of dirty.

The permissions errors are maybe due to the "compaction" dance going on at boot time?

**Comment by springmeyer** [comment]
Yes, the permissions error appears to be because the file is deleted while is being read and windows catches this as impossible because it locks on file handles. Commenting out the [unlink here](https://github.com/mapbox/tm2/blob/23196a54a6d4d3f46b6e8847c437cbeca2eb4d68/lib/tm.js#L46) works around the problem.

**Comment by yhahn** [comment]
Ok cool, I can play around with ways to close the file handle, delete, and then write the new "compacted" db.

**Comment by springmeyer** [comment]
okay, sounds good, will close this and can track at #315.
