### ISSUE TITLE
512 by 512 tiles

### ISSUE THREAD

**Issue by summer4096** [mapbox/mapbox-studio-classic#329]
65,536 pixels isn't cool. You know what's cool? 262,144 pixels.
![reallytho](https://cloud.githubusercontent.com/assets/216009/2820879/4221a3e0-ceff-11e3-9e60-6685163d918f.png)

**Comment by wboykinm** [comment]
:+1: for a 512px endpoint.

**Comment by yhahn** [comment]
Action starting upstream to start.

https://github.com/mapbox/tilelive-vector/issues/53

**Comment by wboykinm** [comment]
Woohoo!

**Comment by yhahn** [comment]
@camilleanne want to prep a pull req for your `512` branch?

Since https://github.com/mapbox/tm2/issues/357 will be following it up and represents a more complete UI for print, I'm thinking:
- Drop the print project pref flag and toggle UI https://github.com/mapbox/tm2/blob/512/lib/style.js#L38
- Continue to switch to @2x automatically based on `devicePixelRatio` for retina screens.
- Maybe just a small message `Showing @2x tiles` / `Showing @1x tiles1 to assure users of what they're seeing.

We can merge that into master and then follow up with the dedicated print/export/stitch UI.

**Comment by camilleanne** [comment]
@yhahn cool-- I'll take a look once I get to Stockholm (~1.5 hr).

**Comment by camilleanne** [comment]
https://github.com/mapbox/tm2/pull/399

**Comment by camilleanne** [comment]
Hey, merged. Huzzah.

**Comment by wboykinm** [comment]
Whee!
