### ISSUE TITLE
Closing New Layer should drop back into map

### ISSUE THREAD

**Issue by ingalls** [mapbox/mapbox-studio-classic#334]
![tm2confusing](https://cloud.githubusercontent.com/assets/1297009/2893731/78a9ecea-d54b-11e3-802d-a368c672c8eb.gif)

If the user is adding a new source and changes their mind, closing the modal, it should drop the user back into the environment where they came from, not the layers environment.

**Comment by aaronlidman** [comment]
This is tricky because of the :target selector usage and because we use this same 'add a layer' modal to add another layer to existing source, so sometimes the behavior is desired. Falling back to style mode wouldn't always apply, and when it does we don't have a straightforward way of remembering which style it came from to direct back to.

**Comment by yhahn** [comment]
@aaronlidman did this.
