### ISSUE TITLE
Exporting stitched images

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#357]
Once better handling of retina and higher DPI tiles are unlocked it's tempting to provide a nice flow for users to render static map images from TM2 styles.
- [x] Add a route at `/image` or `/static` or so that loads a style,
- [x] Provides a display-only UI for picking an image viewport/other settings for exporting,
- [x] Use [leaflet-image](https://github.com/mapbox/leaflet-image) or some other method (? serverside?) to export a stitched image. Curious how this will work with hidpi tiles...
- [x] Add a UI path to get to this from the style editor

Per https://github.com/mapbox/tm2/issues/30

**Comment by srsjojo** [comment]
I'm not a developer ~~(but I stayed at a Holiday Inn Express last night)~~ so I'm not sure if Python will play well with TM2, but I've been using a modified version of [this guy](http://www.instructables.com/id/Animated-Watercolour-Map-for-Cycle-TourRace-Video/step7/Using-the-Functions/) `overlay.py` script to stitch together any tiles I can get my hands on. Stamen, TM2, MapBox, @samanpwbb's [Assemblage](https://a.tiles.mapbox.com/v3/saman.h6ek9086/page.html?secure=1#2/22.3/-75.2) etc. Let me know if you need to see my tweaks.

**Comment by crofty** [comment]
I wrote a ruby gem to stitch together static tiles (https://github.com/crofty/mapstatic) writing a similar package for node would be simple.  However, I'm not sure if this is the approach that TM2 should take.  It would be preferable to come up with a solution that allowed PDF's and SVGs to be exported (Tilemill1 has this functionality).

Stitching SVG tiles together isn't easy and so I think it'd better to get mapnik to do the rendering of the whole image, rather than stitching the pieces together after rendering.  Is this possible when vector tiles are the datasource?  It's sort of what I was asking in https://github.com/mapbox/tm2/issues/30 but I still haven't been able to work it out.

**Comment by camilleanne** [comment]
In branch export-static we now have a 'print' feature which will export the viewport in either 72 dpi, 144 dpi (if on a retina screen), or 288 dpi. It's doing this serverside with [node-blend](https://github.com/mapbox/node-blend/). This is accessible through the Settings menu.

Current API is: `localhost:3000/static/{z},{x},{y}/{px}x{py}{scale}.png?id={tmstyle}` where `x` and `y` are `lon` and `lat` respectively (not tile grid coordinates), and `px` and `py` are dimensions of the viewport in pixels. Scale is denoted with `@1x`, `@2x`, and `@4x` for 256x256, 512x512, and 1024x1024 tiles.

I would like this to:
- [ ] transition from using pixel x and pixel y values to bounds in lon, lat.

This is a very rough interface-- more of a POC.

**Comment by tmcw** [comment]
> transition from using pixel x and pixel y values to bounds in lon, lat.

geo-viewport is an encapsulation of that trick: https://github.com/mapbox/geo-viewport

**Comment by e-n-f** [comment]
I've got a lat-lon-oriented fractional tile stitcher too, if it's any help, at https://github.com/ericfischer/tile-stitch

**Comment by yhahn** [comment]
@camilleanne to start sketching out the UI to hook up to this endpoint,
- Duplicate these files for a starting point
  
  ```
  // client side JS for style page
  app/style.js
  // html template for style page
  template/style._
  ```
- Add a `/print` route or so that is a c/p of the style page route and switch it to use the print template https://github.com/mapbox/tm2/blob/master/index.js#L69

**Comment by camilleanne** [comment]
Here's a current braindump on what I'd like to see in the UI, or at least what I'm thinking about.

#### Current API:

`/static/{z},{x},{y}/{px}x{py}{scale}.{format}`
e.g. `/static/2,4,4/800x800@2x.png`

#### Future API:

something like `/static/{z}/{x,y of top-left}/{x,y of bottom-right}/{scale}.{format}`
    or
if you provide the current API, it calculates the bounds in terms of corner coordinates and reroutes. This might be reasonable as a mirror to the current static API-- also, what is the nature of requests? Are they looking for pixel boundaries or geographic? Who will use the API on it's own?

#### Potential/Future features for UI:

Main Map/Style area:
- Lng,Lat overlay grid/graticule (this will need to autoscale with zoom level)
- Bounding box

Settings/Context area: 
- Navigation box
  - small, world view with dimensions of bounding box
- Set filename (with default)
- Limits
  - Calculation for limit of tiles or pixels rendering
  - Toggle for low vs. high resolution
- Estimate final image size (see templates/exportsize._ in tm2)
- Interface for limits (e.g. you can export this at zooms 1, 2, or 3)
- Loading calculation (for loading bar or spinner)
- Clear explanation of 'print button' - 'export a high resolution png of this area at zoom 7'
- 'Save this print area' which would add a title, the zoom, the top-left corner coords, and the bottom-right corner coords to a object for later reference

##### Looking at:
- [OSM Export](http://www.openstreetmap.org/export#map=15/59.9094/10.7368)
- TileMill Source Export
- TM2 #full
- TM2 /new/source (except it would be /new/print)

I think that the current interface of selecting a bounding box by pixels is a bit of a trap because the pixel bounding box will stay the same while the geographic bounds change when zooming. I think geographic bounds (e.g. top-left corner, bottom-right corner) is consistent, but will require context.

**Comment by camilleanne** [comment]
This functionality exists now in `master`: https://github.com/mapbox/tm2/pull/428.
