### ISSUE TITLE
Compositing local sources

### ISSUE THREAD

**Issue by JesseCrocker** [mapbox/mapbox-studio-classic#368]
The ability to composite multiple remote Mapbox sources together into a single source is great. It's seems like it should be possible to do the same thing with local sources. This may seem like an odd request, but it would be very useful when working on a display style that is designed to be rendered from multiple tile sets, and developing the tile sets at the same time.

**Comment by wboykinm** [comment]
:+1: 

@yhahn are there technical or licensing limitations on the ability to composite a local source on a remote one? It's definitely not working on my setup.

![sources](https://cloud.githubusercontent.com/assets/735463/4414968/a3baafc2-4522-11e4-979f-edb6fa4024ba.gif)

I think I would find the platform rapidly-limiting if I'm unable to easily (read: without quickly filling up my account storage allotment hosting sources) combine my own data with the tremendous resources of Mapbox Data.

**Comment by yhahn** [comment]
Currently only remote sources can be composited -- the compositing is done by the mapbox api at the moment. At some point I can try a sketch of local + remote compositing but am unsure of whether the experience will be desirable given that the performance of local sources is far less consistent/reliable.

**Comment by tnightingale** [comment]
As an exercise to get familiar with the tilelive.js pipeline I whipped this up: https://github.com/tnightingale/tilelive-vector-composite. I'm not sure if there's a way to load external tilelive.js modules into Mapbox Studio but you can use it with tessera (https://github.com/mojodna/tessera) and a modified tilelive-xray module (https://github.com/tnightingale/tilelive-xray/commit/c7fb632d5dcbd770ccb8ac27b2355b82c89e3e3f). 

There's certainly opportunity for improvement but it is functional as a read-only, proof-of-concept.

Without caching, compositing 1 remote (mapbox) datasource with 1 local data source is pretty slow (~1 sec per tile on my laptop + network) which I imagine is primarily due to http overhead. Could definitely improve with better caching and real parallelization of tile fetching.

**Comment by wboykinm** [comment]
@tnightingale Thanks for testing that.

**Comment by JesseCrocker** [comment]
Guessing nothing will ever happen with this, and i've stopped using this software, so issue closed.

**Comment by georgbachmann** [comment]
No update on that one? Anybody knows if Mapbox Studio will ever support that feature? I mean, remote sources can do that... Why can't local ones?

**Comment by wilhelmberg** [comment]
No current plans to do so.
Citing @yhahn from above:

> ...  the compositing is done by the mapbox api at the moment. ... [I] am unsure of whether the experience will be desirable given that the performance of local sources is far less consistent/reliable.

**Comment by georgbachmann** [comment]
That was in 2014... Is it still up to date?

**Comment by wilhelmberg** [comment]
yes.
