### ISSUE TITLE
Lane lines

### ISSUE THREAD

**Issue by digitalsadhu** [mapbox/mapbox-studio-classic#391]
Is there anyway I could roughly calculate lane information so I can go about plotting data on a map split into 2 lanes instead of a single road? My initial naive thought was to simple treat the osm node data as the middle of the road and create 2 parallel lines at a certain distance from the centre adjusting for zoom level but of course that doesn't work for anything more than the most trivial road grids (and even then its not ideal)

An example of the type of use:

![screen shot 2014-05-23 at 6 17 33 pm](https://cloud.githubusercontent.com/assets/1177098/3069022/e46aba20-e295-11e3-950e-d5d59a7f3a0a.png)

**Comment by tmcw** [comment]
Hm, this is a tough issue - I'd probably solve it by joining all roads, buffering them to make them into thin polygons, and then turning the polyline boundaries into lines. But that's a pretty hacky solution.

Closing, since this is far outside the scope of mapbox-studio, which is a design tool and doesn't do spatial analysis of this type - look to [python+Shapely](https://pypi.python.org/pypi/Shapely), for instance, for that.
