### ISSUE TITLE
Hide/fix upload button

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/mapbox-studio-classic#403]
![screen shot 2014-05-29 at 12 39 23 am](https://cloud.githubusercontent.com/assets/58878/3114050/68bc05a0-e6eb-11e3-821e-67e5147b06b8.png)

These seem to have broken. They are showing for all users, upload should only be visible to users with tm2z access.

I can grab this later this week, or you can grab it. Yes, you.

**Comment by aaronlidman** [comment]
@yhahn Do we not want to hide "Upload"? https://github.com/mapbox/tm2/commit/6ba39a9962b2cceb48d40e08558faa4f0c9cd7cd#diff-e0044d1143eba9adb7df43f567ead2bdL128

**Comment by yhahn** [comment]
This is fine, I can look at fixing the visuals here and making sure users get an appropriate error message for now.

Ref https://github.com/mapbox/tm2/commit/4b36ede4689001b741ab12022ecd56b056eecd16.

**Comment by camilleanne** [comment]
This is currently hidden because clicking on upload, even if it's not enabled on your account, gives you a 'success!' message even if nothing happened. It was very misleading.

Fixed here: https://github.com/mapbox/tm2/commit/b2be851c478cb435a605d0d9088c36ca7a17b1b4

![screen shot 2014-06-17 at 12 00 51 pm](https://cloud.githubusercontent.com/assets/3952537/3306169/62c0a64c-f65e-11e3-8e00-4a9fde285221.png)

**Comment by aaronlidman** [comment]
Cool, we should fix it then. Reopening this to keep it on the radar.
