### ISSUE TITLE
Source UI tests

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#409]
We'll need to add this to do https://github.com/mapbox/tm2/issues/407.

For a quick overview of how we're doing style UI tests:
- Script that runs the tests https://github.com/mapbox/tm2/blob/master/test/test-client.sh using [phantomjs](http://phantomjs.org/)
- The actual tests that run in the browser for the style UI https://github.com/mapbox/tm2/blob/master/app/test/app.test.js

Give these a quick read through and then we can plot doing the same for the source UI.

**Comment by GretaCB** [comment]
Initial tests merged (https://github.com/mapbox/tm2/commit/611afb6979193226353e6ac0966291874cd0f6bd), but possibly room for more.

**Comment by GretaCB** [comment]
Update:
When running `test/test-client.js`, getting the following error...

```
mapboxs-MacBook-Pro-2:tm2 mapbox$ test/test-client.js 
TM2 @ http://localhost:3001/
2014-07-02 20:18:43.196 phantomjs[16854:507] GetSupportedLanguages returns empty language array - CFLocale functions likely failing
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/846AEBF2-3852-474D-B6AE-6AFC4D43E558.dmp
2014-07-02 20:18:47.616 phantomjs[16856:507] GetSupportedLanguages returns empty language array - CFLocale functions likely failing


PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/26AA78D9-3526-4937-9AC4-1F00CC68091A.dmp
```

**Is anyone else seeing this error?**

According to PhantomJS's Crash Reporting page, a person is to "attach" the `.dmp` file to a new issue, but it is impossible to attach it since Github doesn't allow attaching a `.dmp` file. Also, they prefer that the .dmp file be converted to a stack trace, but this can only be done using a Linux machine, which I do not have. 

I mainly want to check to see if anyone else is getting this error before diving deeper.

/cc @samanpwbb @yhahn

**Comment by yhahn** [comment]
I'll look into this -- likely the changes I made to get our client-tests running Windows is triggering something that breaks in Mac OS X.

Fun times : )

**Comment by GretaCB** [comment]
Thanks for taking a look @yhahn ! Let me know if I can help in any way.

**Comment by yhahn** [comment]
We're in a good spot here. Closing.
