### ISSUE TITLE
Add files: Drag & Drop

### ISSUE THREAD

**Issue by GretaCB** [mapbox/mapbox-studio-classic#431]
Enable drag & drop for adding new files (discussion here https://github.com/mapbox/tm2/issues/171)

**Comment by springmeyer** [comment]
Can't wait :)

**Comment by yhahn** [comment]
So one challenge here:
- what the tm2 UI is _not_ doing when you select a file in the browser is uploading it or looking at its contents.
- what the tm2 UI _is_ doing when you select a file is telling the server (and thus eventually mapnik) what absolute filepath to inspect and eventually read.

As far as I know the browser file API (which is what gets used once you drag + drop something) does not expose the absolute path to the file dragged which is considered a security risk. So you may have the basename of the file (e.g. `bus_routes.shp`) but not the full path to it (e.g. `/path/to/bus_routes.shp`).

I think taking a quick poke at this to confirm this is next but otherwise I think we'll be blocked here : |

**Comment by tmcw** [comment]
> As far as I know the browser file API (which is what gets used once you drag + drop something) does not expose the absolute path to the file dragged which is considered a security risk.

Yes, this is the case. [node-webkit](https://github.com/rogerwang/node-webkit) changes this and gives you the full path, but there's no other workaround that doesn't suck.

**Comment by yhahn** [comment]
Yeah node-webkit is kind of dead to me as a story atm unfortunately -- I've seen too many ppl using tm2 on servers/headlessly/not directly on their computer.

**Comment by incanus** [comment]
>  does not expose the absolute path to the file dragged 

Correct, see background also in https://github.com/mapbox/tm2/issues/230.

**Comment by incanus** [comment]
This could however be solved on a per-platform basis. For example on OS X it would be possible to: 
1. Identify in the window/view that a file was being dragged in. 
2. Get the full path to it. 
3. Modify the DOM in some way to pass the path. 

Related: https://github.com/mapbox/tm2/issues/110

**Comment by tmcw** [comment]
FWIW: is it a horrible idea to actually upload the file rather than using it in place? I picture this kind of like a powerpoint presentation: sometimes you have references to files, but usually it burns you.

This would <strike>break</strike> take up disk space with gigantic files, but with moderate ones, I almost picture this like expected / useful behavior.

Or it may be a horrible idea.

**Comment by yhahn** [comment]
Putting this on ice. This is a victory lap kind of task : ) let's win all the other battles first.
