### ISSUE TITLE
Static UI: Optimizing workflow using exact dimensions

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-studio-classic#438]
Capturing chat conversation with @camilleanne:

For printing maps, I think it will be common for users to have a final print size and dpi in mind. How can we optimize the workflow for them to create their composition under their own constraints?

Example scenario:
You want to make a print that's 9"x12" with a 0.25" bleed on all sides at the highest possible resolution (288ppi). So therefore you can calculate that your bounding box should be 2736 x 3600 pixels (9.5_288 x 12.5_288), and adjust the handlebars of the bounding box accordingly (although if you adjust your zoom level, you'll need to adjust your bounding box again). 

@camilleanne just added handlebars to the center of the bounding box edges so you can constrain your resizing to one dimension, which I think helps enormously. She's also going to add calculated dimensions in inches underneath the pixel dimension (which is based on the pixel dimension and the selected resolution). I think this will help too, so users don't need to do the conversion themselves.

Ideally, I think that users should have the option of inputting their desired dimensions rather than only being able to drag the bounding box, but as @camilleanne noted, it's a bit complicated since the dimensions of the bounding box will change if you change the zoom level. Are there good ways we can implement this? Can we add more control without making it confusing?
- @camilleanne suggestion of using ratios (e.g. 3:4) rather than dimensions?
- Adjusting the geographic area of the bounding box if the user checks an option to constrain the bounding box by dimension?
- Maybe it's just ok for the dimensions to change if the user changes zoom level? 
- Maybe we don't need this, and the two updates @camilleanne made above are enough to aid in creating correctly-sized images?

/cc @amyleew @samanpwbb

**Comment by amyleew** [comment]
@camilleanne 

The fact that zooming changes the dimensions so drastically seems like a big usability problem. Is there a way users can "lock" dimensions? So as they zoom it keeps that dimension and maybe re-sizes the boundaries from the center point? This is similar conceptually to the ratio idea but could be more intuitive since the actual dimensions are what user would be after.

Also is there a way to indicate (perhaps in red) that the area of scale is out of bounds for print? That would save a step from them clicking the "download static map" button and getting an "Error: Desired image is too large."

**Comment by camilleanne** [comment]
@amyleew @nickidlugash 

So, as far as zooming in and maintaining dimensions goes, I was trying to stay away from that. But if you would like to see an example of it in the wild, it exists here: http://maps.stamen.com/m2i/#toner/1500:1000/12/37.7706/-122.3782

I like the idea of ratios, that makes a lot of sense to me. Constraining an image size to specific dimensions seems hard for zoom, yes, but also seems a bit silly because isn't more better? Like a 'measure twice, cut once' deal? It seems better to have a larger image in the right shape that you can resize (or not, most printers are happy to get a higher ppi image). Am I wrong?

Some of the fixes Nicki and I talked about last night are in (inches and ppi https://github.com/mapbox/tm2/pull/428#commits-pushed-5d489ac). Since error handling from the server is weird, I'm trying to make it so there's no way you can send a parameter through that will create an error in the image (other than timing out because your machine is slow, that is beyond my control). If the image is too big, the download button is disabled and the link is gone. 

Here are some gifs of the magic 'too big, cant download' feature, also, the image size % per zoom level grid. Is that a helpful feature?

![tm2print21](https://cloud.githubusercontent.com/assets/3952537/3303668/f2f8022c-f641-11e3-844f-70fe689e5912.gif)
![tm2printppi](https://cloud.githubusercontent.com/assets/3952537/3303670/f6c8d278-f641-11e3-9db4-ef7d976d5061.gif)

**Comment by amyleew** [comment]
@camilleanne i like the constraining stamen example. i suggest it's a toggle on/off feature. if a user has a specific size and area in mind, it's ideal to set that once and then zoom in our out for detail. easier and faster than having to go back and resize on each zoom.

more is great! unless it exceeds the render size. and it's a bit disorienting. plus, for higher zooms you may want to specific more detail with a cropped location.

i love the too large red text and disabled button treatment. maybe add some text to indicate that as well... \* too large to render

**Comment by camilleanne** [comment]
@amyleew I actually strongly dislike the Stamen implementation, but that's why we're having this conversation, perspective is good :)

I'm punting on these for now for export-print-ui v2. I'd like to see how this plays out for a few days so we can make sure I'm spending time on the right tools for this. In the meantime, this is done! https://github.com/mapbox/tm2/pull/428

**Comment by amyleew** [comment]
@camilleanne just curious... do you dislike the overall implementation or specifically how it constraints? that's really the only part I liked...

**Comment by camilleanne** [comment]
https://github.com/mapbox/tm2/pull/454 seems to have fixed this
