### ISSUE TITLE
Static UI: Image Capture Button

### ISSUE THREAD

**Issue by amyleew** [mapbox/mapbox-studio-classic#470]
talked with @nickidlugash on this and she had a good point on why this works this way... _BUT_ wonder if it disorients users more than helps them.
#### use case:  print a bookmarked location, DC
- select the bookmark, screen jumps to location, DC
  ![screen shot 2014-06-24 at 7 51 05 pm](https://cloud.githubusercontent.com/assets/4587826/3379982/284cc7b4-fbfb-11e3-8193-30ffd76b86b8.png)
- in settings, click image button
- the screen is then moved **back to the previously printed screen**, which was SF, the bounds are set and zoom is reset to that previous print location as well
  ![screen shot 2014-06-24 at 7 51 18 pm](https://cloud.githubusercontent.com/assets/4587826/3379986/48d72664-fbfb-11e3-96de-e4a820758502.png)
- i select my bookmark location again and screen jumps back to where i want it DC
  ![screen shot 2014-06-24 at 7 51 38 pm](https://cloud.githubusercontent.com/assets/4587826/3379993/760c3200-fbfb-11e3-840f-251717a0cefd.png)
- i hit 'reset bounds to zoom' button, and it sets _BUT_ then takes me **back a zoom level**
  ![screen shot 2014-06-24 at 7 51 46 pm](https://cloud.githubusercontent.com/assets/4587826/3380004/b27e8cc4-fbfb-11e3-806c-44e1d31c1d24.png)_bookmark is set to z14 but that button knocks me back to z13_

i feel like these two issues 1) resetting to previously printed bounds and zoom and 2) 'reset bounds to zoom' button knocking you down a zoom, are both disorienting to users, particularly new users. 

thoughts?

/cc @yhahn @samanpwbb @camilleanne

**Comment by camilleanne** [comment]
@amyleew Interesting, I hadn't spent much time thinking about the flow between style/image. It's not actually 'resetting to the previously printed bounds', it's just setting the center of the map in the print view to the center passed to the print view by the style view, and that center is the center coordinate for the last time you saved the style. (don't read that sentence out loud. she sells seashells by the seashore, or something)

However, I did add the "center bounds" button just for that use case of ending up somewhere else but wanting to keep your current bounding box dimensions and zoom. I went back and forth on whether it should be 'recenter' or 'center bounds' or 'recenter bounds.' Thoughts?

For clarity, the reason why it zooms out when you reselect within the viewport is that if it didn't zoom out, you wouldn't have access the the sides or corners of the box for resizing since they would be at the edges of the viewport. I considered having the bounding box reselect to just before the edges of the viewport and not zooming out, but couldn't decide because that's also a bit of a lie since it's not actually selecting the entirety of the viewport.

**Comment by samanpwbb** [comment]
Agree with @amyleew about the zoom out upon clicking 'reset bounds' button is disorienting. I couldn't really figure out what it did for a while. The "center bounds" button feels more useful and understandable.

**Comment by amyleew** [comment]
@camilleanne  i see why you made it zoom out. but now that why have the 'center bounds' function (which is awesome! and maybe 'center bounds to view' as the name), do we even need 'reset'?

users will be looking to alter the output dimensions as well as area to output. this interaction, is now much more intuitive since 1) they can edit the dimensions in right side panel and 2) set the bounds to 'center' on the current view. i think that's more helpful than seeing the bounding box edges... plus, the zoom level shift is disorienting. if you go in and drag the map around, and click to compare the 'center' against the 'reset' button, you'll notice how it just follows your lead and it feels like a much more fluid experience.

**Comment by camilleanne** [comment]
Cool, lets lose the 'reset bounds to view' button for now. Since the dimensions are so easily modifiable, it's pretty superfluous. https://github.com/mapbox/tm2/commit/b415e35073c72bcc4acc0658d6cc4cf6c25105f1

That doesn't solve the confusion around where you end up on the map when you select the 'image' button.

**Comment by amyleew** [comment]
Ideally the functionality would keep the user on the same screen as they navigate between both the Styling UI and Printing UI.

**Comment by camilleanne** [comment]
Rolling this into https://github.com/mapbox/tm2/issues/553
