### ISSUE TITLE
Build error in mapnik

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapbox-studio-classic#59]
@springmeyer -

Just tried to build tm2 but I get this error in building mapnik:

https://gist.github.com/lxbarth/743434dc5d44ef376a42

I have this feeling I'm including wrong headers from somewhere but not sure how to debug this.

**Comment by springmeyer** [comment]
I'm working on binaries right now, so you can wait a few hours for those.

Or to get this working update your Mapnik install to the v2.2.0 release via homebrew. Check the readme for details: https://github.com/mapbox/tm2/blob/master/README.md#mac-os-x

I think the problem is you have a pre-release v2.2.0 mapnik install.

**Comment by lxbarth** [comment]
Thanks @springmeyer - will give this a shot.

**Comment by springmeyer** [comment]
@lxbarth - if you continue to have any trouble, know that you can also just grab a standalone binary for OS X: https://github.com/mapbox/tm2/blob/master/README.md#binary
