### ISSUE TITLE
Export Image Pattern size/resolution 

### ISSUE THREAD

**Issue by g12n** [mapbox/mapbox-studio-classic#634]
The size of a patter is absolute. 
In Carto is no to set the tile-size of a polygon-pattern-file. 

This results in Problems when exporting an image. The pattern shrinks down more and more, relative to it's surrounding map.

**Comment by g12n** [comment]
# Example of the effect of resolution on pattern

| 300ppi | 600ppi |
| --- | --- |
| ![osm bright 2-z10_6 221_53 2085_7 0175_53 7146_4](https://cloud.githubusercontent.com/assets/57556/3854615/1693e8de-1eda-11e4-99cd-44b77796280c.jpeg) | ![osm bright 2-z10_6 221_53 2085_7 0175_53 7146_8](https://cloud.githubusercontent.com/assets/57556/3854616/1a755f32-1eda-11e4-8600-c5f85fb22fb6.jpeg) |

In Core this is a Carto or Mapnik problem but there are Several possible Sollutions:

## multiple files (srcset)

Like the [srcset in html](http://responsiveimages.org/) the `polygon-pattern-file` could take multiple source-files depending on the resolution of the target-medium. This would work for Retina-Versions of maps als well. 

For higher Resolutions (especially export) mapbox-studio could chose the correct file before haninding it to carto. Or Carto choose it before handing it to Mapnik. 

## polygon-pattern-size

Completing Carto with a parameter `polygon-pattern-size` would ease the workflow using pattern for different zooms and resolutions. 

Different sizes could be precompiled before handing them to Mapnik. This way you could even add Support ´.svg´support for polygon-patterns.

**Comment by springmeyer** [comment]
Mapnik 3.x just landed support for scaling patterns and for patterns being based on svg. Mapbox-studio will be upgrading to Mapnik 3.x very soon. I'll ping back here when a new build is ready to test. Until then see some of the action over at https://github.com/mapnik/mapnik/issues/1010.

**Comment by TheMapSmith** [comment]
It looks like this issue also applies to pixel based arguments such as `translate()`. Notice the tree shadows in 1x vs 4x. I had to manually pull up an 4x tile and keep fiddling with the `translate()` to figure out how to align the shadow for print.
![107911@1x](https://cloud.githubusercontent.com/assets/8357118/4142278/edd3e542-33b6-11e4-925e-0c9485b116f8.png)
![107911@4x](https://cloud.githubusercontent.com/assets/8357118/4142283/f2f609ec-33b6-11e4-8be5-451e23c53e71.png)

*Could the user force-render retina mode in the browser so that you could quickly proof print outputs? 

*Or could pixel values be multiplied by the scale? So that if `translate(5,3)` looks right in 1x tiles it would render 4x tiles with `translate(20,15)`?

Thanks,
~Stephen

**Comment by samanpwbb** [comment]
@g12n latest release of Mapbox Studio uses mapnik 3, which supports SVG patterns. These will scale with the map. 

@TheMapSmith your issue is a bit different. All the mapnik `transform` functions ignore scale factor, while the `geometry-transform` functions take scale into account. See https://github.com/mapnik/mapnik-reference/pull/86
