### ISSUE TITLE
Can't upload, export, or download

### ISSUE THREAD

**Issue by jczaplew** [mapbox/mapbox-studio-classic#691]
OS X 10.9.4, cloned mapbox-studio an hour ago. If I create and save a source (locally), and then create and save a style, I am unable to upload to Mapbox, export an image, or download a package, as the options are disabled. Hopefully I'm just missing a step in the process - presumably something with not having a map ID? I'm not seeing an errors in the console or terminal. 

![screen shot 2014-08-20 at 2 27 10 pm](https://cloud.githubusercontent.com/assets/1739551/3987080/0ad7933e-28a2-11e4-935d-27d14fc458c7.png)

**Comment by yhahn** [comment]
Yep, just save your project.

**Comment by jczaplew** [comment]
Is there another saving step besides saving the source and the style?

**Comment by yhahn** [comment]
Nope -- but note hitting (ctrl+s) is not the same as clicking `Save as` to save the project to disk (it's still just in memory until you do the last step).

**Comment by jczaplew** [comment]
(Really, really sorry for how slow I am) Is clicking `Save as` the same as clicking the `Save` icon? 
![screen shot 2014-08-20 at 3 49 19 pm](https://cloud.githubusercontent.com/assets/1739551/3987957/7f42ec7e-28ab-11e4-90f2-8bdcb1630860.png)

**Comment by yhahn** [comment]
@jczaplew hrm, if those options are disabled and your project is saved then it sounds like this is a bug. Does this happen to you for all style/source projects you're working on?

(The **Save** button is only labeled **Save as** when you first start a new project)

**Comment by jczaplew** [comment]
Yes. Just to verify, I repeated the process again -
1. Create new source
2. Add shapefile
3. Select "Save as..." and save it locally
4. Select "Create style from this source"
5. Modified default style
6. Select "Save as..."
7. Saved style locally
8. Select "Settings", and the upload/export/download options were still disabled

**Comment by camilleanne** [comment]
@jczaplew the source you are using -- did you upload it to Mapbox.com or are you styling it from a local source?

Upload, Export, and Download are disabled for styles referencing a local source that has not been uploaded to Mapbox.com. A reference to a source stored locally on your machine wouldn't mean anything once uploaded since Mapbox.com would not have access to it.

Make sure the source you are using has been uploaded -- you can check this by:
1. opening your source, opening the Settings pane, and seeing if there is a `Map ID`
or 
2. In your style, open the Layers pane and see if under the name of your source file is _remote_ or _local_

**Comment by ajashton** [comment]
Ran into related issues just now:
1. Export Image should not be disabled for styles that use a local source.
2. Changing from a local source to a remote source & saving does not re-enable export/upload until Studio is restarted (or refreshed in browser mode).

**Comment by junosuarez** [comment]
Also seeing this bug on the windows build (win32-ia32-v0.0.4) - using local source, export is disabled for style.

**Comment by yhahn** [comment]
Addressed by https://github.com/mapbox/mapbox-studio/pull/722
