### ISSUE TITLE
auto-centering is too far zoomed in

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#854]
When adding new sources, especially those with broad geographic bounds, I usually end up with this screen:

![screen shot 2014-09-17 at 4 09 48 pm](https://cloud.githubusercontent.com/assets/108094/4310460/a6dade48-3ea6-11e4-9904-27806b8cfe08.png)

**Comment by yhahn** [comment]
Upstream in mapnik-omnivore.

**Comment by GretaCB** [comment]
Hey @samanpwbb, this is set [here in mapbox studio](https://github.com/mapbox/mapbox-studio/blob/mb-pages/app/source.js#L347). `metadata` is the info coming from `mapnik-omnivore`. 

Originally I was setting zoom level for the map view to `maxzoom - 1`, but this was zooming out too much for some files. This was a tricky middle ground, because if a file has very little data, like city border of DC (DC_polygon.geojson file in `mapnik-test-data`), it will appear too zoomed out and hard to see. 

This will also affect [the zoom-to feature](https://github.com/mapbox/mapbox-studio/blob/mb-pages/app/source.js#L639).

**Comment by GretaCB** [comment]
@samanpwbb @yhahn I can also play around in mapnik-omnivore with setting maxzoom to a larger/smaller number depending on if avg tilesize is less than 1000 (some threshold for "less data per tile"?
- less data in the tiles -> larger the maxzoom
- more data in the tiles -> smaller the maxzoom

to help buffer this a bit.

**Comment by yhahn** [comment]
@samanpwbb @GretaCB hrm... I don't know if there is a perfect zoom level that can be autodetected easily for every datasource without actually doing a lot of work and finding tiles in the source that have data. `maxzoom - 1` has worked pretty well for most sources so far. Other things I've tried in the past:
- minzoom
- the exact middle zoom between minzoom and maxzoom (e.g. for 0-10 => 5)

There are always corner cases for these.

**Comment by samanpwbb** [comment]
> maxzoom - 1

This sounds better than maxzoom. Then, minzoom runs into issue where tiles don't render at z0 or z1 (due, i think, to size issues with vector tiles).
