### ISSUE TITLE
Sources Map ID error

### ISSUE THREAD

**Issue by flemmens** [mapbox/mapbox-studio-classic#856]
Another bug in Windows version:

In the Layers tab, if I try to change the source, the map ID displayed is incorrect.
For instance, my map is: "tmsource://c/Users/FLP/Countries.tm2source"
When I go to local source, then choose my map in the list, it displays:
"tmsource://c:/Users/FLP/Countries.tm2source", with a : after the c, which is incorrect, the source won't load, I have to manually correct the map ID before clicking on Apply.

Also, I tried to add several sources by adding a comma between map IDs as stated in the comment but it does not work, the apply button don't work. How can I add several sources ? (for instance my local source and the remote mapbox streets) ??

**Comment by camilleanne** [comment]
@flemmens We've got a fix for the path issue coming up.

But regarding compositing multiple sources, you can only composite remote sources. 

If you want to composite a custom source with Mapbox Streets for instance, you will need to upload your custom source to Mapbox.com from the source view. Sources can be uploaded without a Standard account. If you would like to upload your style to Mapbox.com you would need to be using a remote source regardless since we can't reference your local sources from our servers. We limit uploads for style to ones with remote sources.

**Comment by flemmens** [comment]
Uploading our data on Mapbox is not an option. 1) Our license model do not allow us to export these data on third party servers 2) The size is about 500Gb which means the upload would take days to complete 3) Your biggest plan offer a total storage of 30Gb which is a way to small.

In my opinion, the greatest advantage of studio compare to tilemill would be the possibility to combine customized Mapbox layers with local layers, then export the combined sources into a unique vector tiles database to be served from anywhere (mapbox or local servers depending the needs).

If I understand you correctly, it is not possible to export customized mapbox tiles locally, is that right ? In this case we do not see any interest in using studio instead of tilemill and we will wait for tilemill 2 to be able to use vector tiles (any news on this side ? It's been almost 3 years since the last tilemill update, do you still plan to support this software ?)

**Comment by markiliffe** [comment]
@camilleanne could you shed some light on @flemmens question? I'm dealing with gigabytes of data - not as much as @flemmens but big enough, seeing as I already pay for Mapbox (but at a level where I don't need to mortgage my flat) exporting maps would be rather useful...

**Comment by miccferr** [comment]
@camilleanne I second @markiliffe and @flemmens request. 

Actually I've seen quite a share of confusion on the interwebz regarding Studio's Local Sources. 

For instance, you are saying that "..regarding compositing multiple sources, you can only composite remote sources". 
But in the GUI if I browse to Layers -> Change Source -> Local there's a (possibly)misleading text indication under the "local path" toolbar.. 
Is that a bug or am I missing something? (see attached image)

![schermata 2015-02-25 alle 23 01 31](https://cloud.githubusercontent.com/assets/3855777/6381567/544a1d9a-bd42-11e4-8c77-45afa2f39a6e.png)

And what about the case when you are dealing with not uploadable data, as @flemmens is asking (say for privacy/license concerns)..
Am I, de facto, forced not to use Studio altogether since I have to upload such data on my Mapbox account? 

Thanks in advance for your answer!

**Comment by camilleanne** [comment]
@flemmens + @markiliffe Mapbox Studio is "Tilemill 2" -- Tilemill being for the creation and styling of raster tiles and Mapbox Studio for the creation and styling of vector tiles. The use case you put forth (huge amounts of proprietary data that you cannot distribute, but would benefit from Mapbox data and layers) is a good candidate for [Atlas Server](https://www.mapbox.com/enterprise/atlas/) which provides a Mapbox.com environment, but on your own servers, and also integrates with Mapbox Studio.

We offer Mapbox Streets as an mbtiles download for Atlas Server users -- but Mapbox Streets is an enormous file which is why we only offer it to enterprise. Also the most up to date version of Mapbox Streets exists as individual tiles on our servers, not an mbtiles file.

@miccferr I've ticketed out what you are seeing and a clearer explanation in that UI will be in a future release. You're right, it's misleading. If you had tried to composite two local sources, you would have gotten an error, even though the hint implies you can. And if you have data you cannot upload to Mapbox.com,  [Atlas Server](https://www.mapbox.com/enterprise/atlas/) is your best bet.

Also, if you have your own map server that is capable of serving map tiles compatible with Mapbox.js, you can composite Mapbox maps with your own data following this pattern: https://www.mapbox.com/mapbox.js/example/v1.0.0/layers/ with Mapbox Streets being served from Mapbox.com, and your data served from your own server.
see also: https://www.mapbox.com/mapbox.js/api/v2.1.5/l-mapbox-tilelayer/
