### ISSUE TITLE
.gpx file not autodetecting projection when adding source

### ISSUE THREAD

**Issue by runsnowdonia** [mapbox/mapbox-studio-classic#859]
Attempting to add .gpx file as layer in new source in Mapbox Studio. The .gpx file looks fine, however when adding it as a layer the Projection is listed as: +init=epsg:4326 and when the 'fields' tab is clicked the following: "No available fields. Make sure your layer is referencing valid data."

.gpx file content:

![gpsbabel 18092014 100145](https://cloud.githubusercontent.com/assets/8612588/4317388/bb0150f2-3f12-11e4-8f03-2e65148a7dba.jpg)

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<gpx>
<trk>
<trkseg>
<trkpt lat="53.080415000" lon="-4.021359000"><ele>375.7</ele><time>2014-09-05T15:31:49Z</time></trkpt>
<trkpt lat="53.080419000" lon="-4.021410000"><ele>376.9</ele><time>2014-09-05T15:31:52Z</time></trkpt>
<trkpt lat="53.080423000" lon="-4.021584000"><ele>377.8</ele><time>2014-09-05T15:32:00Z</time></trkpt>
<trkpt lat="53.080436000" lon="-4.021753000"><ele>378.4</ele><time>2014-09-05T15:32:05Z</time></trkpt>
<trkpt lat="53.080439000" lon="-4.021919000"><ele>379.0</ele><time>2014-09-05T15:32:09Z</time></trkpt>
<trkpt lat="53.080453000" lon="-4.022084000"><ele>380.4</ele><time>2014-09-05T15:32:13Z</time></trkpt>
<trkpt lat="53.080463000" lon="-4.022242000"><ele>382.2</ele><time>2014-09-05T15:32:17Z</time></trkpt>
<trkpt lat="53.080441000" lon="-4.022391000"><ele>384.0</ele><time>2014-09-05T15:32:21Z</time></trkpt>
<trkpt lat="53.080451000" lon="-4.022583000"><ele>385.8</ele><time>2014-09-05T15:32:25Z</time></trkpt>
</trkseg>
</trk>
</gpx>
```

**Comment by GretaCB** [comment]
@springmeyer the projection is `+init=epsg:4326` because currently, mapnik-omnivore [assumes projection for gpx and kml](https://github.com/mapbox/mapnik-omnivore/blob/master/lib/datasourceProcessor.js#L117).

@springmeyer should this still be assumed?

And I ran the gpx file above through `mapnik-omnivore` and Mapbox Studio, and fields are coming out fine. This ticket might've been related to [a bug with gpx files back in Sept](https://github.com/mapbox/mapbox-studio-internal/issues/117) that was fixed.

**Comment by springmeyer** [comment]
@GretaCB - thanks! Yes, the assumed `+init=epsg:4326` is correct, but the `No available fields. Make sure your layer is referencing valid data.` seems odd. However I just tested the above data and the fields load fine so I think you are right that this was fixed in 
https://github.com/mapbox/mapbox-studio-internal/issues/117

![screen shot 2014-11-19 at 12 55 36 pm](https://cloud.githubusercontent.com/assets/20300/5114200/7c4e3a8c-6feb-11e4-8e65-a7f5adb0367b.png)
