### ISSUE TITLE
Rendering of light colored roads against light background

### ISSUE THREAD

**Issue by makella** [mapbox/mapbox-studio-classic#86]
Hello,

I'm working with TileMill 2 building our National Park Service basemap Park Tiles.  I hope this is an OK place to post a question/issue I'm seeing.

For the 'streets' class I'm using a light color with no casing at zooms 12 and 13, zoom>=14 I'm adding a casing.

At z12 and z13, I'm noticing that the light lines against the lightish background of my map are not rendering properly.  If I change the lines to a darker color, they are rendering fine.  Please see attached images.

![streets-powder](https://f.cloud.github.com/assets/1566273/1734848/96c75468-634c-11e3-9d80-0fba6ef2c5ff.png)

![streets-red](https://f.cloud.github.com/assets/1566273/1734850/9e934d6e-634c-11e3-9525-545d738601d5.png)

When the same streets class is viewed against a darker background, they are rendering just fine (you'll notice the difference of rendering between the dark/light background in this image):

![streets-background](https://f.cloud.github.com/assets/1566273/1734900/471c56ce-634d-11e3-862b-c09806377aa5.png)

And this is what they look like at larger scales with the casing:

![streets-casing](https://f.cloud.github.com/assets/1566273/1734871/d997a7ac-634c-11e3-9f0b-78c86ce628ea.png)

Anyone experienced a similar issue?

Thanks for any help!

mamata

**Comment by springmeyer** [comment]
My hunch is that this is due to the default image format used in TM2: png with colors reduced to 256. You can click on the project name to get its settings and try changing the format to full color png. However, to have this work (and actually request a full color PNG you'll need my fix from just now: e9fd312b0c89de53e84fbb0354761425b8856a8c). A binary build for OS X based on this commit `e9fd312` should show up in about 25 minutes at this link: http://tilemill.s3.amazonaws.com/index.html?path=dev/
