### ISSUE TITLE
Mapbox Studio osm_id is limited to 32 bits or somehow some osm_id have negative numbers

### ISSUE THREAD

**Issue by baditaflorin** [mapbox/mapbox-studio-classic#879]
poi_label
address 
localrank 5
maki shop
name Librăria Luceafărul
name_de Librăria Luceafărul
name_en Librăria Luceafărul
name_es Librăria Luceafărul
name_fr Librăria Luceafărul
network 
osm_id -501911073
ref 
scalerank 4
type Books
website 
![negative osm id](https://cloud.githubusercontent.com/assets/2330999/4377556/ff73b1f8-434f-11e4-9403-7f4b9ecc76ee.png)

http://www.openstreetmap.org/node/501911073

**Comment by ajashton** [comment]
Hi,

osm_ids in the mapbox-streets vector tile source are modified from the original osm_ids in order to avoid conflicts between the overlapping number spaces of nodes, ways, and relations. See the OSM IDs section of the [Mapbox Streets vector tiles documentation](https://www.mapbox.com/developers/vector-tiles/mapbox-streets/) for details about the transformations.

**Comment by baditaflorin** [comment]
hmm, this kind of complicate my idea.

I want to use Mapbox studio beyond making a map, i want to use it as a analyst tool to show the age of a POI

The idea is that if a restaurant or club POI is older then 5 years, let`s say , is possible that that amenity is now closed. 

I was looking to make a map that show old poi in different colors, to know the poi that we need to verify on mapillary or do a on the ground survey to make sure the poi still exist

**Comment by ajashton** [comment]
You could do that, but it would have to be with a [custom vector tile source](https://www.mapbox.com/mapbox-studio/source-quickstart/) since the mapbox-streets vector tiles do not contain any modification date information. (The osm_id can be a useful approximation of the object's creation time, but its common for very old objects to be kept up-to-date with recent edits.)

If your idea is to correlate mapbox-streets vector tile data with raw osm data, I think these transformations will help you because if you just have an osm id of '12345' you have no way of knowing whether it is node 12345, way 12345, or relation 12345. (Objects in the poi_label layer can come from any of the 3 types of objects.) With the modified id in mapbox-streets you know they type of object from the range it falls into, and you can easily get the original osm id with a reverse transformation.
