### ISSUE TITLE
Document expressions (waiting on mapnik 3.x.x)

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#881]
See https://github.com/mapnik/mapnik-reference/pull/79

**Comment by springmeyer** [comment]
Just a note that this can be tested before actually upgrading to Mapnik 3.x (since mapnik-reference and carto don't actually depend on Mapnik 3.x directly) by flipping the `2.3.x` to `latest` in the places evident in https://github.com/mapbox/mapbox-studio/pull/768/files.

But yes, once Mapnik 3.x is actually released then I'll add a new mapnik-reference entry for `3.0.x` we can point at.

**Comment by samanpwbb** [comment]
Closed with  https://github.com/mapbox/mapbox-studio/commit/ee167be69acfb89ae2bf354a692399364aa007f0 in `mapnik3` branch.

**Comment by springmeyer** [comment]
\o/
