### ISSUE TITLE
Allow search by multiples in Places

### ISSUE THREAD

**Issue by amyleew** [mapbox/mapbox-studio-classic#892]
It would be cool to be able to search by more than just one feature, location or OSM tag in the Places search box.

![image](https://cloud.githubusercontent.com/assets/4587826/4426847/8407a40a-45b8-11e4-9e2c-b60ca9bbe0a5.png)

/cc @samanpwbb

**Comment by nickidlugash** [comment]
Let's implement AND as default, with an OR option. Maybe this?:

"[firstWord] [secondWord]" = AND
"[firstWord] OR [secondWord]" = OR

@amyleew FYI for roads, this is going to return partial matches for tags, so that e.g. if you search for "road path", this will return not only "road, path", but also "tunnel, path", "road, street" etc. Currently if you just search "road, path" (with the comma), you'll return everything tagged as "road, path".

**Comment by samanpwbb** [comment]
> "[firstWord] [secondWord]" = AND

Ya, definitely

> "[firstWord] OR [secondWord]" = OR

I would prefer to implement just 'and' to start, and if there continues to be demand for more flexibility, we can add an OR keyword or UI for doing similar as a next step.

**Comment by nickidlugash** [comment]
If we implement this, I guess we'll have to wrap exact phrases in quotation marks? E.g. "road, main" or "osm data"?

> "[firstWord] OR [secondWord]" = OR

I think this would be useful in the cases where you want to style two features the same way – e.g. you want to style road:service the same as road:driveway. For now you could do two separate searches, but it would be nice to see these in one search.

**Comment by samanpwbb** [comment]
Just talked with @nickidlugash @amyleew - 

Freeform search is not the future of the places interface. It's too easy to get no results because the scope of the search is so limited, and currently the UI doesn't do a good job of managing user expectations: "How come there's _another_ search on the map toolbar? What sorts of things am I supposed to search for here vs there?".

Instead, we should pursue a tag-first UI for filtering. @amyleew is going to sketch some user flows for what this could look like.

**Comment by nickidlugash** [comment]
@samanpwbb Just to clarify – are you thinking that we should get rid of the search entirely? I think tag browsing should be the main way to interact with Places, but I also like that right now you can search for sub-strings, e.g. so that searching "road" will return "road:path:steps", etc, and "road:path" will return "road:path:steps", etc.

**Comment by samanpwbb** [comment]
'road' could just be a tag. There would be no substring searching based on the proposal in my comment above. I am ok with this, as allowing substring matches leads to a mental model that suggests that freeform searching is going to work for a user. In reality, freeform searching leads to a lot failed searches.

**Comment by nickidlugash** [comment]
@samanpwbb this would mean that, e.g., an entry with 'road:path:steps' would also need tags for both 'road' and 'road:path'. And every city tagged 'city:scalerank1', 'major city', etc would also need to be tagged 'city', and every poi tagged 'poi:scalerank1', 'poi:museum' would also need to be tagged 'poi'. I'm fine with this, but just want you to be aware that this will mean a lot of additional tags. I am not going to implement these additional tags until we launch this redesign of the UI.

**Comment by samanpwbb** [comment]
@nickidlugash you and @amyleew should sketch wireframes for how you want this to work. The UI should come first, and then adjustments to the gazetteer data structure should follow to match. If you want to be able to filter by both "road", "road path" and "road path steps", which it sounds like you do, lets first figure out what a UI for that should look like then adapt everything else to follow.

**Comment by amyleew** [comment]
@nickidlugash @samanpwbb  - First pass on sketches for UI... Tag browsing could function as a a filtering tool that you can either refine or expand. 

General UI allowing users to search by feature which is either a layer, class or class type. Shows all available tags, categorized by #layer then listing classes and class types.

![image](https://cloud.githubusercontent.com/assets/4587826/4447224/2d9747b2-4809-11e4-9065-75f6f9a01513.png)

Filter Up would expand the search by adding tags you get additional results based on that feature.

![image](https://cloud.githubusercontent.com/assets/4587826/4447390/6a11a1e6-480a-11e4-83e9-b94bd0440ef6.png)

Filter Down would limit the search by specific tags which also could drill down to types nested across multiple layer classes such as path type trail in #bridge vs. path types in #roads.

![image](https://cloud.githubusercontent.com/assets/4587826/4447431/c18e7246-480a-11e4-9e7c-2a419ea0396e.png)

Landmarks - could be a section in addition to Features that contains general (non Mapbox Street or OSM named) geographical POI-type tags that we curate. Like... Disney, resorts in Dubai, Yosemite, etc. Landmarks can be for uses cases like how @nickidlugash envisioned it to explore areas around the world. Features is more functional to QA like @samanpwbb uses or test styling like I use it.

![image](https://cloud.githubusercontent.com/assets/4587826/4447473/048c9960-480b-11e4-9dcc-f7e51e66a688.png)

**Comment by amyleew** [comment]
Tracking on fresh ticket - https://github.com/mapbox/mapbox-studio/issues/920
