### ISSUE TITLE
timeout on new session

### ISSUE THREAD

**Issue by dalekunce** [mapbox/mapbox-studio-classic#941]
Studio crashes (timesout) on initial load everytime. I can continue by cancelling the error message and selecting a default project and then selecting my personal project.

![screen shot 2014-10-10 at 8 57 19 am](https://cloud.githubusercontent.com/assets/1913857/4592570/46910902-507d-11e4-9f63-1e9f11c77afa.png)

**Version 0.1.5 (darwin)**
**OS:** Mac OS X 10.9.5

**Comment by springmeyer** [comment]
We had sporadic reports of this for studio v0.1.5 and v0.1.6 but none since the v0.2.0 release. Will close this issue, but please create a new issue if you see this again @dalekunce. I'll note that it could occur for a variety of reasons. One that may occur again is if you are offline so anyone testing make sure you are connected to the internet :)
