### ISSUE TITLE
Loading postgis layer has rendering issues

### ISSUE THREAD

**Issue by ramotswa** [mapbox/mapbox-studio-classic#970]
Hello,
So what I've done;
New project  - blank - + New Layer
Select import from postgis
Enter all the details (including the confusing table name into the freetext box)
It seems to add it but with a few problems;
A: It doesn't seem to calculate autoextent, which means it doesn't zoom to my area which means I have to do an actual search for my location (with the very very handy search tool).
B: Once I've zoomed to my location, the rendering is very wierd: it seems to have simplified the polygons massively and so all I can see are straight or vertical lines. (Image attached).

The layers are either in 900913 or wgs84, and I pick the right projection accordingly. 

I can view all of the layers in QGIS fine, so I'm not sure it's a db error.

Any help would be appreciated.

Thanks
Ramo

![image](https://cloud.githubusercontent.com/assets/778529/4807081/8366b70c-5e90-11e4-8019-5926c3ae1964.png)

**Comment by TheMapSmith** [comment]
I had the same rendering problem when I was setting up sources. @ajashton helped me out with the solution [here](https://twitter.com/aj_ashton/status/496159356472541184)

The twitter link is dead due to file name changes, but this is the new doc: 
https://github.com/mapbox/mapbox-studio/blob/mb-pages/docs/0000-01-01-source-manual.md

**Solution: In the Source Settings panel (top left), increase the max zoom setting**

The sources panel is still the wild west of this project. Let me know if you need any other help.

**Comment by ramotswa** [comment]
Hi Steven, that's great thanks - worked a charm. 

I am now trying to label polygons as described in your link (i.e. use the sql query to get a point geometry), and the query works fine in pgadmin, but not so well in mapbox studio.. have you ever gotten that to work?

Cheers,
Ramo

**Comment by TheMapSmith** [comment]
Ramo,

I haven't done the polygon to point query that they talk about in the document so I'm not sure I can help you there, sorry.

The way I've learned about the queries is by looking at other repositories for examples.

Here is the NaturalEarth source configuration file:
https://github.com/mapbox/natural-earth-tm2/blob/master/natural-earth.tm2source/data.yml

And here is the most advanced one I've seen - OpenStreetMap Carto. The source format is different, but you can still see the queries.
https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml

~Stephen
